### ISSUE TITLE
Installation Failed in Python 3.6.5 version

### ISSUE THREAD

**Issue by avell1** [FilippoBovo/robustats#12]
I tried installing robustats from 0.1.2 to 0.1.7 all the versions in python 3.6.5

i am getting below error 

Microsoft Visual C++ 14.0 required. But I do have Visual C++ greater than 14. 

ERROR: Failed building wheel for robustats

**Comment by FilippoBovo** [comment]
Hi, @avell1. Did you try installing the Microsoft C++ Built Tools?

https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by avell1** [comment]
Thanks. This helped to install the robustats
