### ISSUE TITLE
Inconsistent results on Jupyer notebook and Intellij IDE: Python

### ISSUE THREAD

**Issue by Iravata** [FilippoBovo/robustats#14]
I am trying to compute medcouple using robustats module in python

The results on jupyter note book and IntelliJ Ide do not match.

Result on my **jupyter notebook:**

```
from robustats import medcouple
import numpy as np

x = np.array([9325.06, 6206.00, 10000.00, 9569.78])
print(medcouple(x))

-0.6442066420664204
```
Result on **IntelliJ Ide**

```
from robustats import medcouple
import numpy as np

x = np.array([9325.06, 6206.00, 10000.00, 9569.78])
print(medcouple(x))

nan
```

Please do let me know if I have to change any setting on IDE. I have made sure both are running against the same virtual env

**Comment by FilippoBovo** [comment]
Hi, @Iravata. Thank you for submitting this issue.

Could you please let me know what versions of Python and Numpy you are using?

**Comment by Iravata** [comment]
Hi @FilippoBovo .
I am using the below versions
numpy - 1.21.0
python - 3.9.4

**Comment by FilippoBovo** [comment]
Are the versions the same in IntelliJ and Jupyter?

**Comment by Iravata** [comment]
yes they both are same

**Comment by FilippoBovo** [comment]
Hmm, then it is a bit odd.

Could you try to use simple lists, instead of Numpy arrays?

```python
from robustats import medcouple

x = [9325.06, 6206.00, 10000.00, 9569.78]
print(medcouple(x))
```

**Comment by Iravata** [comment]
If I use normal list the result matches. I think the issue is with numpy
```
from robustats import medcouple
import numpy as np

x = np.array([9325.06, 6206.00, 10000.00, 9569.78])
print(medcouple(x))
x = [9325.06, 6206.00, 10000.00, 9569.78]
print(medcouple(x))
```

and the results are.

```
nan
-0.6442066420664204
```

**Comment by FilippoBovo** [comment]
Ok, then it may be a precision issue, that is, robustats using floats, rather than doubles.

Just in case, could you check the dtype of the Numpy array in Jupter and IntelliJ (`x.dtype`)?

If the dtypes are different, you may try to define the Numpy array setting an explicit dtype, like the following.

```python
x = np.array([9325.06, 6206.00, 10000.00, 9569.78], dtype=np.float64)
```

However, I am not sure that this is the problem, as it may also be due to the C compiler that you use to compile the Robustats library.

**Comment by Iravata** [comment]
`x = np.array([9325.06, 6206.00, 10000.00, 9569.78], dtype=np.float64)`

even this is returning nan

**Comment by FilippoBovo** [comment]
Ok. Could you try to create new virtual environments with Python 3.8 and the latest version of Numpy and try again, using the same virtual environment in Jupyter and IntelliJ?

**Comment by Iravata** [comment]
sure will try that .. and let you know

**Comment by Iravata** [comment]
I tried it on a different machine, with Python 3.8 and numpy - 1.21.0 . I dont see the issue very strange.

**Comment by FilippoBovo** [comment]
Ok. Then, I think that the issue might have been with your previous installation of Numpy. Let me know if this issue can be closed. Otherwise, I would need to have enough details to be able to reproduce the issue myself in order to solve it.

**Comment by Iravata** [comment]
ok we can close it. I will get back to you if i get more inofrmation.

**Comment by FilippoBovo** [comment]
Ok. Thanks.
