### ISSUE TITLE
Install failed  with Python 3.7.7 on Windows

### ISSUE THREAD

**Issue by daknoll** [FilippoBovo/robustats#3]
Is robustats available for Python 3.7.7?  I get the following error when I try to   install with "pip install robustats".  Install worked fine with Python 3.6.       (py37) t=21:23:20 path="C:\"   >pip install robustats   Collecting robustats     Using   cached robustats-0.1.4.tar.gz (11 kB)   Requirement already satisfied: numpy in   c:\users\e1256736\documents\dk\apps\miniconda\miniconda3\envs\py37\lib\site-packages   (from robustats) (1.18.1)   Building wheels for collected packages:   robustats       Building wheel for robustats (setup.py) ... error       ERROR: Command errored out with exit status 1:        command:   'C:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\python.exe'   -u -c 'import sys, setuptools, tokenize; sys.argv[0] =   '"'"'C:\\Users\\e1256736\\AppData\\Local\\Temp\\pip-install-ar9k5ced\\robustats\\setup.py'"'"';   __file__='"'"'C:\\Users\\e1256736\\AppData\\Local\\Temp\\pip-install-ar9k5ced\\robustats\\setup.py'"'"';f=getattr(tokenize,   '"'"'open'"'"',   open)(__file__);code=f.read().replace('"'"'\r\n'"'"',   '"'"'\n'"'"');f.close();exec(compile(code, __file__,   '"'"'exec'"'"'))' bdist_wheel -d   'C:\Users\e1256736\AppData\Local\Temp\pip-wheel-564ycb78'            cwd:   C:\Users\e1256736\AppData\Local\Temp\pip-install-ar9k5ced\robustats\       Complete output (12 lines):       running bdist_wheel       running build       running build_py       creating build     creating   build\lib.win-amd64-3.7       creating build\lib.win-amd64-3.7\robustats       copying robustats\robustats.py -> build\lib.win-amd64-3.7\robustats       copying robustats\__init__.py -> build\lib.win-amd64-3.7\robustats       running build_ext     No   module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from   distutils       building '_robustats' extension       error: Microsoft Visual C++ 14.0 is required. Get it with "Build   Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/       ----------------------------------------       ERROR: Failed building wheel for robustats       Running setup.py clean for robustats   Failed to build robustats   Installing collected packages: robustats         Running setup.py install for robustats ... error         ERROR: Command errored out with exit status 1:          command:   'C:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\python.exe'   -u -c 'import sys, setuptools, tokenize; sys.argv[0] =   '"'"'C:\\Users\\e1256736\\AppData\\Local\\Temp\\pip-install-ar9k5ced\\robustats\\setup.py'"'"';   __file__='"'"'C:\\Users\\e1256736\\AppData\\Local\\Temp\\pip-install-ar9k5ced\\robustats\\setup.py'"'"';f=getattr(tokenize,   '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',   '"'"'\n'"'"');f.close();exec(compile(code, __file__,   '"'"'exec'"'"'))' install --record   'C:\Users\e1256736\AppData\Local\Temp\pip-record-pkbp5lg5\install-record.txt'   --single-version-externally-managed --compile --install-headers   'C:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\Include\robustats'              cwd:   C:\Users\e1256736\AppData\Local\Temp\pip-install-ar9k5ced\robustats\         Complete output (12 lines):         running install         running build         running build_py         creating build         creating build\lib.win-amd64-3.7         creating build\lib.win-amd64-3.7\robustats         copying robustats\robustats.py -> build\lib.win-amd64-3.7\robustats         copying robustats\__init__.py -> build\lib.win-amd64-3.7\robustats         running build_ext       No module   named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from   distutils         building '_robustats' extension         error: Microsoft Visual C++ 14.0 is required. Get it with "Build   Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/         ----------------------------------------   ERROR: Command errored out with exit status   1:   'C:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\python.exe'   -u -c 'import sys, setuptools, tokenize; sys.argv[0] =   '"'"'C:\\Users\\e1256736\\AppData\\Local\\Temp\\pip-install-ar9k5ced\\robustats\\setup.py'"'"';   __file__='"'"'C:\\Users\\e1256736\\AppData\\Local\\Temp\\pip-install-ar9k5ced\\robustats\\setup.py'"'"';f=getattr(tokenize,   '"'"'open'"'"',   open)(__file__);code=f.read().replace('"'"'\r\n'"'"',   '"'"'\n'"'"');f.close();exec(compile(code, __file__,   '"'"'exec'"'"'))' install --record   'C:\Users\e1256736\AppData\Local\Temp\pip-record-pkbp5lg5\install-record.txt'   --single-version-externally-managed --compile --install-headers 'C:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\Include\robustats'   Check the logs for full command output.
--

**Comment by FilippoBovo** [comment]
Hi, @daknoll.

Thank you for raising the issue.

The error you pasted states:

```
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
```

Can you try installing Microsoft Visual C++ 14.0 and then install `robustats`?

**Comment by daknoll** [comment]
I installed the Build Tools for Visual Studio and now get different errors listed below.  I'm just curious though why a binary build was not required when I installed robustats for Python 3.6.

(py37) t=15:30:49 path="C:\"
>pip install robustats
Collecting robustats
  Using cached robustats-0.1.4.tar.gz (11 kB)
Requirement already satisfied: numpy in c:\users\e1256736\documents\dk\apps\miniconda\miniconda3\envs\py37\lib\site-packages (from robustats) (1.18.1)
Building wheels for collected packages: robustats
  Building wheel for robustats (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\e1256736\\AppData\\Local\\Temp\\pip-install-tt95xvuc\\robustats\\setup.py'"'"'; __file__='"'"'C:\\Users\\e1256736\\AppData\\Local\\Temp\\pip-install-tt95xvuc\\robustats\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\e1256736\AppData\Local\Temp\pip-wheel-ssb57ksr'
       cwd: C:\Users\e1256736\AppData\Local\Temp\pip-install-tt95xvuc\robustats\
  Complete output (23 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\robustats
  copying robustats\robustats.py -> build\lib.win-amd64-3.7\robustats
  copying robustats\__init__.py -> build\lib.win-amd64-3.7\robustats
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  building '_robustats' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\c
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\lib\site-packages\numpy\core\include -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\include -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcc/_robustats.c /Fobuild\temp.win-amd64-3.7\Release\c/_robustats.obj -std=c99
  cl : Command line warning D9002 : ignoring unknown option '-std=c99'
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\lib\site-packages\numpy\core\include -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\include -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcc/robustats.c /Fobuild\temp.win-amd64-3.7\Release\c/robustats.obj -std=c99
  cl : Command line warning D9002 : ignoring unknown option '-std=c99'
  robustats.c
  C:\Users\e1256736\AppData\Local\Temp\pip-install-tt95xvuc\robustats\c\base.h(3): error C2059: syntax error: '<parameter-list>'
  c/robustats.c(101): warning C4244: 'function': conversion from 'int64_t' to 'double', possible loss of data
  c/robustats.c(261): warning C4244: '=': conversion from 'int64_t' to 'double', possible loss of data
  error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\lib\site-packages\numpy\core\include -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\include -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcc/robustats.c /Fobuild\temp.win-amd64-3.7\Release\c/robustats.obj -std=c99" failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for robustats
  Running setup.py clean for robustats
Failed to build robustats
Installing collected packages: robustats
    Running setup.py install for robustats ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\e1256736\\AppData\\Local\\Temp\\pip-install-tt95xvuc\\robustats\\setup.py'"'"'; __file__='"'"'C:\\Users\\e1256736\\AppData\\Local\\Temp\\pip-install-tt95xvuc\\robustats\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\e1256736\AppData\Local\Temp\pip-record-y13dq_ds\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\Include\robustats'
         cwd: C:\Users\e1256736\AppData\Local\Temp\pip-install-tt95xvuc\robustats\
    Complete output (23 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\robustats
    copying robustats\robustats.py -> build\lib.win-amd64-3.7\robustats
    copying robustats\__init__.py -> build\lib.win-amd64-3.7\robustats
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    building '_robustats' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\lib\site-packages\numpy\core\include -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\include -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcc/_robustats.c /Fobuild\temp.win-amd64-3.7\Release\c/_robustats.obj -std=c99
    cl : Command line warning D9002 : ignoring unknown option '-std=c99'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\lib\site-packages\numpy\core\include -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\include -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcc/robustats.c /Fobuild\temp.win-amd64-3.7\Release\c/robustats.obj -std=c99
    cl : Command line warning D9002 : ignoring unknown option '-std=c99'
    robustats.c
    C:\Users\e1256736\AppData\Local\Temp\pip-install-tt95xvuc\robustats\c\base.h(3): error C2059: syntax error: '<parameter-list>'
    c/robustats.c(101): warning C4244: 'function': conversion from 'int64_t' to 'double', possible loss of data
    c/robustats.c(261): warning C4244: '=': conversion from 'int64_t' to 'double', possible loss of data
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\lib\site-packages\numpy\core\include -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\include -IC:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcc/robustats.c /Fobuild\temp.win-amd64-3.7\Release\c/robustats.obj -std=c99" failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\e1256736\\AppData\\Local\\Temp\\pip-install-tt95xvuc\\robustats\\setup.py'"'"'; __file__='"'"'C:\\Users\\e1256736\\AppData\\Local\\Temp\\pip-install-tt95xvuc\\robustats\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\e1256736\AppData\Local\Temp\pip-record-y13dq_ds\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\e1256736\Documents\DK\Apps\Miniconda\Miniconda3\envs\py37\Include\robustats' Check the logs for full command output.

**Comment by FilippoBovo** [comment]
The only error explicitly stated in the messege you pasted is this:

>C:\Users\e1256736\AppData\Local\Temp\pip-install-tt95xvuc\robustats\c\base.h(3): error C2059: syntax error: ''

Maybe, this error is due to the compiler that you are using, but I am not sure. Also, I do not have Windows. So, it is hard to identify the problem.

>I'm just curious though why a binary build was not required when I installed robustats for Python 3.6.

Are you sure about this? PyPi should not have anything compiled in the package.

**Comment by daknoll** [comment]
I think the error may be due to "#include <stdint.h>" in base.h.  Microsoft Visual Studio has had problems with this include file in the past.  I'm not 100% sure on this and I can't test it out right now.

**Comment by FilippoBovo** [comment]
Yes, that's a possibility.

Please, let me know if you find a solution to this issue. Thank you.

**Comment by jeanollion** [comment]
Hi, I also have issues installing robustats, under linux, python 3.7.7, and no problem under 3.6.9. 
The error message that might help you find the problem: 
Best regards

```

    ERROR: Command errored out with exit status 1:
     command: /home/XXX/.virtualenvs/tensorflow1/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/XXX/.virtualenvs/tensorflow1/src/robustats/setup.py'"'"'; __file__='"'"'/home/XXX/.virtualenvs/tensorflow1/src/robustats/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/XXX/.virtualenvs/tensorflow1/src/robustats/
    Complete output (29 lines):
    running develop
    running egg_info
    writing robustats.egg-info/PKG-INFO
    writing dependency_links to robustats.egg-info/dependency_links.txt
    writing requirements to robustats.egg-info/requires.txt
    writing top-level names to robustats.egg-info/top_level.txt
    reading manifest file 'robustats.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'robustats.egg-info/SOURCES.txt'
    running build_ext
    building '_robustats' extension
    Warning: Can't read registry to find the necessary compiler setting
    Make sure that Python modules winreg, win32api or win32con are installed.
    C compiler: x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-OVQonc/python3.7-3.7.7=. -fstack-protector-strong -Wformat -Werror=format-security -g -fdebug-prefix-map=/build/python3.7-OVQonc/python3.7-3.7.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
    
    compile options: '-I/home/XXX/.virtualenvs/tensorflow1/lib/python3.7/site-packages/numpy/core/include -I/home/XXX/.virtualenvs/tensorflow1/include -I/usr/include/python3.7m -I/home/XXX/.virtualenvs/tensorflow1/include -I/usr/include/python3.7m -c'
    extra options: '-std=c99'
    x86_64-linux-gnu-gcc: c/base.c
    x86_64-linux-gnu-gcc: c/robustats.c
    x86_64-linux-gnu-gcc: c/_robustats.c
    c/_robustats.c:2:10: fatal error: Python.h: Aucun fichier ou dossier de ce type
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    c/robustats.c: In function ‘weighted_median’:
    c/robustats.c:27:19: warning: variable ‘w_middle’ set but not used [-Wunused-but-set-variable]
        double median, w_middle;
                       ^~~~~~~~
    error: Command "x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-OVQonc/python3.7-3.7.7=. -fstack-protector-strong -Wformat -Werror=format-security -g -fdebug-prefix-map=/build/python3.7-OVQonc/python3.7-3.7.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/XXX/.virtualenvs/tensorflow1/lib/python3.7/site-packages/numpy/core/include -I/home/XXX/.virtualenvs/tensorflow1/include -I/usr/include/python3.7m -I/home/XXX/.virtualenvs/tensorflow1/include -I/usr/include/python3.7m -c c/_robustats.c -o build/temp.linux-x86_64-3.7/c/_robustats.o -std=c99" failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/XXX/.virtualenvs/tensorflow1/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/XXX/.virtualenvs/tensorflow1/src/robustats/setup.py'"'"'; __file__='"'"'/home/XXX/.virtualenvs/tensorflow1/src/robustats/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.


```

**Comment by FilippoBovo** [comment]
@jeanollion, I think you may have to install the Python dev tools. See this link: https://stackoverflow.com/a/21530768.

**Comment by 0x4Graham** [comment]
FYI I am getting the same error as above. And the Python dev tools do not assist.

**Comment by FilippoBovo** [comment]
@jeanollion and @Grey007, I installed a fresh Linux Debian distribution, installed `build-essential` and `python3-pip`, installed Python 3.7.7 and installed `robustats` without  any issue.

So, try to install `build-essential`,

```
sudo apt-get install build-essential
```

and then try to install `robustats`. If it still does not work, install `python3-pip`,

```
sudo apt-get install python3-pip
```

If it still does not work, upgrade Numpy to the last version and retry.

Please, let me know if this works.

**Comment by 0x4Graham** [comment]
I’m not on Linux, I’m on Windows.

Kind Regards,
Graham Nelson

________________________________

**Comment by FilippoBovo** [comment]
@Grey007, then you can disregard my comment.

What is the error that you get?

**Comment by szkafander** [comment]
On Windows, the issue is the "max" function defined in base.h - it clashes with Windows' default definition. Change the name of the function or add "#define NOMINMAX" before your #include statements.

**Comment by FilippoBovo** [comment]
Hey, @szkafander. Thanks for your message. As I do not have Windows and assuming that you have it, could you please rename the max function to `max_` and see if it works? If it does, would you be happy to make the change and open a pull request? Thanks!

**Comment by szkafander** [comment]
@FilippoBovo  pull request sent here: https://github.com/FilippoBovo/robustats/pull/11

**Comment by FilippoBovo** [comment]
@szkafander, thanks for the PR. 🙏  The new version (0.1.6) is now live in Pypi and can be installed with Pip.
