### ISSUE TITLE
 module 'robustats' has no attribute 'medcouple'?

### ISSUE THREAD

**Issue by tks1998** [FilippoBovo/robustats#4]

**Comment by tks1998** [comment]
![image](https://user-images.githubusercontent.com/37293650/78754988-9c2bcb00-79a2-11ea-849f-18e4d590edb4.png)

**Comment by FilippoBovo** [comment]
Hi, @tks1998.

What operating system are you using?

**Comment by tks1998** [comment]
I use a notebook from Kaggle.

**Comment by FilippoBovo** [comment]
Can you try to install the package using Pip?

```shell
pip install robustats
```

If you install it using Pip, does it give you the same error?

**Comment by tks1998** [comment]
I was able to run it, thank you!
